name: Build-sphinx-docs

on:
  push:
    branches:
      - master
      - 'stable/**'
  pull_request:
    branches:
      - master
      - 'stable/**'
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs: 
  build: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.12'
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install nox
        run: pip install --upgrade nox ghp-import
      - name: Run docs
        run: | 
          nox -s docs
      - name: Run ghp-import
        run: | 
          ghp-import -n -p -f docs/_build/html
